### ISSUE TITLE
Make run fails with undefined VERSION

### ISSUE THREAD

**Issue by sebastianroesch** [pusher/faros#112]
On the latest version, `make run` fails with
```
cmd/manager/main.go:55:64: undefined: VERSION
```

On build, the version gets passed as a flag with `-ldflags="-X main.VERSION=${VERSION}"`, which doesn't seem to work for `go run`.

For some reason, it does not pick up the `var VERSION = "undefined"` from `cmd/manager/version.go` as a fallback.

**Comment by JoelSpeed** [comment]
We rarely use the `make run` target so I can see why it might not be quite working 😅 Apologies!

I will look into this

**Comment by sebastianroesch** [comment]
Thank you!
