### ISSUE TITLE
Info logs logged to stderr

### ISSUE THREAD

**Issue by sebastianroesch** [pusher/faros#122]
All Faros logs seem to be logged to `stderr`, also all informational logs. In log aggregators like Datadog, they are therefore automatically categorised as errors. This makes it hard to identify actual errors, for example when Faros failed applying a resource.

I assume it is related to this line: `goflag.Lookup("logtostderr").Value.Set("true")`

Is there any good way to configure this currently?
Thanks

**Comment by JoelSpeed** [comment]
This is a common problem/pattern that we've blindly been following for a while now, it's to do with how GLog works by default, or rather, doesn't.

You should be able to set the flag by hand though `--logtostderr=false`

I'm working on logging at the moment in #114 and will keep this in mind

**Comment by sebastianroesch** [comment]
Thanks, I tried it already with `--logtostderr=false`, but they still come out as errors. Isn't this because the code always sets it to `true`, not matter the value of the flag?

**Comment by JoelSpeed** [comment]
Since `flag.Parse()` is called after the set I would have expected that to work 🤔
