### ISSUE TITLE
Faros fails to create custom resources when applied along with CRDs

### ISSUE THREAD

**Issue by sebastianroesch** [pusher/faros#135]
Faros fails creating custom resources when their CRDs are also created by Faros.
Error message: `error getting API resource: unable to get REST mapping: no matches for kind "Schedule" in version "velero.io/v1"`

This error occurs on every `Reconcile` until the Faros pod is restarted. After a restart, Faros successfully creates the custom resource.

This makes it harder to use Faros to automate the cluster creation process, as it requires manual intervention.

My assumption is that the `client-go` REST mapper doesn't know of the CRD yet after it has been created. https://github.com/pusher/faros/blob/master/pkg/utils/rest_mapper.go#L48

Any ideas on how to prevent this? I'm hoping for a better way, but worst case I could imagine restarting Faros after a `Reconcile` that created or updated CRDs.

**Comment by JoelSpeed** [comment]
Hey @sebastianroesch, could you please confirm for me which version of Faros you are running, we saw this issue before and thought we had fixed it in https://github.com/pusher/faros/pull/91.

For context, when the controller starts, it uses the OpenAPI schema from the cluster it connects to to "discover" all resources available, the `FirstHitRestMapper` we have constructed here is meant to use the first discovery for most things and then rediscover for anything not matched by the original discovery. I thought this had fixed the issue though it may need a little bit more exploration.

**Comment by sebastianroesch** [comment]
Hey @JoelSpeed, the version we're running has this change already.

Do we need to make a similar change to the REST mapper here? https://github.com/pusher/faros/blob/master/pkg/utils/rest_mapper.go

I think the error we're seeing is coming from this code.

**Comment by JoelSpeed** [comment]
Good spot! Do you have time to make the fix there too and open a PR? We really should deduplicate that code at some point

**Comment by sebastianroesch** [comment]
Working on it.

**Comment by sebastianroesch** [comment]
I created https://github.com/pusher/faros/pull/136, which solved the issue for me. Took a bit of digging through `client-go` and `apimachinery` to understand how it works :)

**Comment by aaron-trout** [comment]
I was also seeing this on 0.4.0-rc4. #136 does seem to fix this, would be good to get another version tag for this :D

I do still see this though:

```
faros-controller-manager-0 manager 2019/04/24 14:18:31 error getting API resource: unable to get REST mapping: no matches for kind "" in version ""
```

Is this the whole weird thing with RBAC where you have to put `apiversion: ""` sometimes? In the `roleBinding`?

**Comment by JoelSpeed** [comment]
@aaron-trout I'm not entirely sure where these errors come from but I'm pretty sure they're benign. We see them occasionally too. I guess it could be that it's unmarshalled a yaml that doesn't contain those fields set? Should have bailed earlier than that though 🤔 

Im going to close this issue as it has been resolved, feel free to open another for the empty apiversion if you like
