### ISSUE TITLE
Introduction of snyk dependency breaks docker-test

### ISSUE THREAD

**Issue by sebastianroesch** [pusher/faros#142]
Since snyk has been added as a dependency in https://github.com/pusher/faros/commit/51eaaa1171018a97e9c2e829d91cecd1d300ca97#diff-44584acc21d3880fcbe7e1e5e9afc3ebR41, `make docker-test` fails for us as there is no `npm` available in the Docker image and it's not being installed.

**Comment by mthssdrbrg** [comment]
Hiya. I'm afraid I'm not following, there isn't any `docker-test` target in the Makefile? 

```bash
$ make docker-test
make: *** No rule to make target 'docker-test'.  Stop.
```

From what I can tell only the `scan` and `docker-scan` targets require snyk. I haven't been able to find any (other) target that depends on snyk being installed.

**Comment by sebastianroesch** [comment]
Hi, you are right, sorry, the `docker-test` is a target we introduced. Closing this issue.

It uses the `prepare-env-%` command, which installs snyk using npm, but there is no npm in the Docker image we're using for the tests.
