### ISSUE TITLE
Disable namespaced flag when using ClusterGitTracks

### ISSUE THREAD

**Issue by JoelSpeed** [pusher/faros#182]
I tried to use the controller with `--gittrack-mode=Enabled`, `--clustergittrack-mode=ExcludeNamespaced` and `--namespace=kube-system`, expecting the controller to be able to process ClusterGitTracks normally, however the informers were limited to the `kube-system` namespace and as such it exhibited weird behaviour.

I would like to propose that the `--namespace` flag be mutually exclusive from `ClusterGitTracks` being enabled.

CC @DanielMorsing

**Comment by DanielMorsing** [comment]
Specifically, this will mess up on the namespace of secrets, requiring `ClusterGitTracks` to all have the same namespace for their secrets as their namespace limiting.

This is an unusual mode of operation and explaining the counter-intuitive behavior would be hard, so I'm inclined to agree on the mutually exclusive nature of these flags
