### ISSUE TITLE
Error installing crds

### ISSUE THREAD

**Issue by jaxxstorm** [pusher/faros#75]
Seems there's an issue with the crd definition?

```
error: error validating "generated/do/pharos/01-crds.yaml": error validating data: [ValidationError(CustomResourceDefinition.status): missing required field "conditions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionStatus, ValidationError(CustomResourceDefinition.status): missing required field "storedVersions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionStatus]; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by JoelSpeed** [comment]
Hi, thanks for raising this issue, this is probably due to a Kubernetes versioning mismatch, could you just confirm for me which version of Kubernetes you are trying this with?

**Comment by jaxxstorm** [comment]
v1.12

It works if you change the storedVersions status to an empty array instead of null

**Comment by JoelSpeed** [comment]
We are currently running `controller-tools` with dependencies on Kubernetes 1.11, when this is upgraded to 1.12 (I'm working on a bug fix which will include this, should be ready within the next few days) then the auto generated manifests will be upgraded to be compatible with the newer version, I will link this issue when I open that PR as it should solve the problem
