### ISSUE TITLE
GitTrack `status` should list ignored files

### ISSUE THREAD

**Issue by gargath** [pusher/faros#79]
When encountering files that do not contain Kubernetes objects or that have been explicitly ignored by config, each gittrack-controller will simply ignore them.

It does count the number of ignored files in the status, but does not give a clue as to which files were ignored.

In addition, GitTrack objects should include in their `status` a breakdown of the file paths and names that were ignored for easy debugging.

**Comment by mthssdrbrg** [comment]
Fixed in #115.
