### ISSUE TITLE
Custom Resources ignored if CRD doesn't exist on first apply

### ISSUE THREAD

**Issue by gargath** [pusher/faros#80]
If a repository contains custom resources and also the CRDs covering them, it is possible for faros to attempt applying the custom resources first.

This will fail and cause the corresponding files to be `ignored`, even though they would succeed once the CRDs are applied.

In this case, the `faros-gittrack-controllers` need to be restarted in order to re-apply the previously-ignored custom-resources.

**Comment by JoelSpeed** [comment]
When faros starts up, it queries the API for installed resources and creates a RestMapping. This does not ever get updated.

To make sure we can reconcile CRDs that didn't exist initially, we should attempt to refresh the RestMapping if there is an error.

Currently, we init the mapper with a standard RestMapper, instead we can create a FristHitRestMapper that contains the standard RestMapper and a LazyRestMapper. When the standard RestMapper fails (if a CRD has been added after faros starts), the LazyRestMapper will "lazily" load a new rest mapping and this will hopefully contain the previously non-existent CRD.

This should solve the problem.
