### ISSUE TITLE
Improve verbosity of GitTrack status fields

### ISSUE THREAD

**Issue by JoelSpeed** [pusher/faros#84]
The status fields Applied, Discovered, Ignored and InSync on GitTracks are not verbose enough and are confusing for people. These should be clarified.

Suggested alternatives
- `Discovered` -> `ResourcesDiscovered`
- `Applied` -> `ChildrenCreated`
- `Ignored` -> `ResourcesIgnored`
- `InSync` -> `ChildrenInSync`

**Comment by mthssdrbrg** [comment]
Fixed in #105.
